//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PluralsightCoursesWF4Model", "FK_CourseRegistration_Course", "Course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CourseDAL.Course), "CourseRegistration", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CourseDAL.CourseRegistration), true)]

#endregion

namespace CourseDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PluralsightCoursesWF4Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PluralsightCoursesWF4Entities object using the connection string found in the 'PluralsightCoursesWF4Entities' section of the application configuration file.
        /// </summary>
        public PluralsightCoursesWF4Entities() : base("name=PluralsightCoursesWF4Entities", "PluralsightCoursesWF4Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PluralsightCoursesWF4Entities object.
        /// </summary>
        public PluralsightCoursesWF4Entities(string connectionString) : base(connectionString, "PluralsightCoursesWF4Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PluralsightCoursesWF4Entities object.
        /// </summary>
        public PluralsightCoursesWF4Entities(EntityConnection connection) : base(connection, "PluralsightCoursesWF4Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Course> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Course>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Course> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CourseRegistration> CourseRegistrations
        {
            get
            {
                if ((_CourseRegistrations == null))
                {
                    _CourseRegistrations = base.CreateObjectSet<CourseRegistration>("CourseRegistrations");
                }
                return _CourseRegistrations;
            }
        }
        private ObjectSet<CourseRegistration> _CourseRegistrations;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CourseRegistrations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourseRegistrations(CourseRegistration courseRegistration)
        {
            base.AddObject("CourseRegistrations", courseRegistration);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PluralsightCoursesWF4Model", Name="Course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        /// <param name="topic">Initial value of the Topic property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="state">Initial value of the State property.</param>
        public static Course CreateCourse(global::System.Int32 courseID, global::System.String topic, global::System.String location, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Byte state)
        {
            Course course = new Course();
            course.CourseID = courseID;
            course.Topic = topic;
            course.Location = location;
            course.StartDate = startDate;
            course.EndDate = endDate;
            course.State = state;
            return course;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.Int32 _CourseID;
        partial void OnCourseIDChanging(global::System.Int32 value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Topic
        {
            get
            {
                return _Topic;
            }
            set
            {
                OnTopicChanging(value);
                ReportPropertyChanging("Topic");
                _Topic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Topic");
                OnTopicChanged();
            }
        }
        private global::System.String _Topic;
        partial void OnTopicChanging(global::System.String value);
        partial void OnTopicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Instructors
        {
            get
            {
                return _Instructors;
            }
            set
            {
                OnInstructorsChanging(value);
                ReportPropertyChanging("Instructors");
                _Instructors = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Instructors");
                OnInstructorsChanged();
            }
        }
        private global::System.String _Instructors;
        partial void OnInstructorsChanging(global::System.String value);
        partial void OnInstructorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.Byte _State;
        partial void OnStateChanging(global::System.Byte value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> WorkflowID
        {
            get
            {
                return _WorkflowID;
            }
            set
            {
                OnWorkflowIDChanging(value);
                ReportPropertyChanging("WorkflowID");
                _WorkflowID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WorkflowID");
                OnWorkflowIDChanged();
            }
        }
        private Nullable<global::System.Guid> _WorkflowID;
        partial void OnWorkflowIDChanging(Nullable<global::System.Guid> value);
        partial void OnWorkflowIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PluralsightCoursesWF4Model", "FK_CourseRegistration_Course", "CourseRegistration")]
        public EntityCollection<CourseRegistration> CourseRegistrations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CourseRegistration>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "CourseRegistration");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CourseRegistration>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "CourseRegistration", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PluralsightCoursesWF4Model", Name="CourseRegistration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CourseRegistration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CourseRegistration object.
        /// </summary>
        /// <param name="courseID">Initial value of the CourseID property.</param>
        /// <param name="studentName">Initial value of the StudentName property.</param>
        /// <param name="studentEmail">Initial value of the StudentEmail property.</param>
        /// <param name="paymentReceived">Initial value of the PaymentReceived property.</param>
        /// <param name="signedIn">Initial value of the SignedIn property.</param>
        public static CourseRegistration CreateCourseRegistration(global::System.Int32 courseID, global::System.String studentName, global::System.String studentEmail, global::System.Boolean paymentReceived, global::System.Boolean signedIn)
        {
            CourseRegistration courseRegistration = new CourseRegistration();
            courseRegistration.CourseID = courseID;
            courseRegistration.StudentName = studentName;
            courseRegistration.StudentEmail = studentEmail;
            courseRegistration.PaymentReceived = paymentReceived;
            courseRegistration.SignedIn = signedIn;
            return courseRegistration;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                if (_CourseID != value)
                {
                    OnCourseIDChanging(value);
                    ReportPropertyChanging("CourseID");
                    _CourseID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CourseID");
                    OnCourseIDChanged();
                }
            }
        }
        private global::System.Int32 _CourseID;
        partial void OnCourseIDChanging(global::System.Int32 value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                if (_StudentName != value)
                {
                    OnStudentNameChanging(value);
                    ReportPropertyChanging("StudentName");
                    _StudentName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StudentName");
                    OnStudentNameChanged();
                }
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StudentEmail
        {
            get
            {
                return _StudentEmail;
            }
            set
            {
                OnStudentEmailChanging(value);
                ReportPropertyChanging("StudentEmail");
                _StudentEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StudentEmail");
                OnStudentEmailChanged();
            }
        }
        private global::System.String _StudentEmail;
        partial void OnStudentEmailChanging(global::System.String value);
        partial void OnStudentEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PaymentReceived
        {
            get
            {
                return _PaymentReceived;
            }
            set
            {
                OnPaymentReceivedChanging(value);
                ReportPropertyChanging("PaymentReceived");
                _PaymentReceived = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentReceived");
                OnPaymentReceivedChanged();
            }
        }
        private global::System.Boolean _PaymentReceived;
        partial void OnPaymentReceivedChanging(global::System.Boolean value);
        partial void OnPaymentReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SignedIn
        {
            get
            {
                return _SignedIn;
            }
            set
            {
                OnSignedInChanging(value);
                ReportPropertyChanging("SignedIn");
                _SignedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SignedIn");
                OnSignedInChanged();
            }
        }
        private global::System.Boolean _SignedIn;
        partial void OnSignedInChanging(global::System.Boolean value);
        partial void OnSignedInChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PluralsightCoursesWF4Model", "FK_CourseRegistration_Course", "Course")]
        public Course Course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "Course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Course> CourseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Course>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Course>("PluralsightCoursesWF4Model.FK_CourseRegistration_Course", "Course", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
